version: 2
jobs:
  one:
    working_directory: /home/circleci/my_test
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      # working directoryで指定しない場合はprojectという名前のディレクリーでcheckoutされる
      - checkout
      - run: echo 'hoge1'

  two:
    working_directory: /home/circleci/my_test/hoge
    docker:
      - image: circleci/node:8.9.4
    steps:
      - run: echo 'hoge2'
      - restore_cache:
          keys:
            - npm-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      #- run: sudo chown -R circleci:circleci /usr/local/bin /usr/local/lib/node_modules
      
      #- run: sudo npm install -g npm@6.0.1 
      #- run: npm install
  three:
    #working_directory: /home/circleci/my_test
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo 'hoge3'
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
      #- two:
      #    type: approval
      #    requires:
      #      - one
      - three:
          requires:
            - two
