version: 2
jobs:
  one:
    working_directory: /home/circleci/my_test
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - my_test
  two:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo 'hoge2'
  three:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo 'hoge3'
      - attach_workspace:
          at: /home/circleci/my_test
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
        requires:
          - one
      #- two:
      #    type: approval
      #    requires:
      #      - one
      - three:
          requires:
            - two
