version: 2
jobs:
  one:
    working_directory: /home/circleci/my_test
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      # working directoryで指定しない場合はprojectという名前のディレクリーでcheckoutされる
      - checkout
      - run: echo 'hoge1'
      - persist_to_workspace:
          root: /home/circleci
          paths:
          #  - ~
            - my_test
  two:
    working_directory: /home/circleci/my_test/hoge
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo 'hoge2'
      #persist_to_workspaceで保存した内容を以下で指定するディレクトリにコピーする。
      - attach_workspace:
      #    #at: /home/circleci/hogeee
           at: /home/circleci/my_test
           #at: /home/circleci
      #    at: /tmp
  three:
    #working_directory: /home/circleci/my_test
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo 'hoge3'
      #- attach_workspace:
      #    at: /home/circleci/my_hogehoge
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
      #- two:
      #    type: approval
      #    requires:
      #      - one
      - three:
          requires:
            - two
